cookie:
  expiry_days: 30
  key: abcde
  name: st-ecommerce
credentials:
  usernames:
    mary:
      email: marytest.com
      name: Mary
      password: $2b$12$5R3jgTqMaE2x5o0EycAiM.rQG1lumnfM8lGears./1vg23usiL.UW
    sean:
      email: blackseanx@gmail.com
      name: Sean Pai
      password: $2b$12$.yOp3/JyxA4..bWMtPL9AuWtcuBqlwJG2F5sCDBbRF6oDmzJUgVSm
    test_user1:
      email: test@gmail.com
      name: Test_User1
      password: $2b$12$wFoXoIEXwQv/VX1LZW3BQugcPN1Y8J9wX8xZ8cmdZId8rOfLsogDa
preauthorized:
  emails:
  - blackseanx@gmail.com
